<?php
return [
     'academy' => ['en' => 'Academy', 'cn' => '学院']
    ,'accepted' => ['en' => 'Accepted', 'cn' => '答案正确']
    ,'add_group' => ['en' => 'Add Group', 'cn' => '添加班级']
    ,'add_homework' => ['en' => 'Add Homework', 'cn' => '发布作业']
    ,'add_news' => ['en' => 'Add News', 'cn' => '发布新闻']
    ,'add_notification' => ['en' => 'Add Notification', 'cn' => '发布公告']
    ,'add_problem' => ['en' => 'Add Problem', 'cn' => '添加问题']
    ,'administrator' => ['en' => 'Administrator', 'cn' => '管理员']
    ,'admin_system' => ['en' => 'Admin System', 'cn' => '后台系统']
    ,'allgroup' => ['en' => 'All Group', 'cn' => '所有班级']
    ,'all_language' => ['en' => 'All Language', 'cn' => '所有语言']
    ,'all_problem' => ['en' => 'All Problem', 'cn' => '所有题目']
    ,'all_result' => ['en' => 'All Result', 'cn' => '所有结果']
    ,'are_you_sure_to_delete_the_selected_files' => ['en' => 'Are you sure to delete the selected files?', 'cn' => '确定删除选中的文件吗？']
    ,'are_you_sure_to_disable_this_problem' => ['en' => 'Are you sure to disable this problem?', 'cn' => '确定禁用此题目？']
    ,'are_you_sure_to_enable_this_problem' => ['en' => 'Are you sure to enable this problem?', 'cn' => '确定启用此题目？']
    ,'are_you_sure_to_pass_the_group_join' => ['en' => 'Are you sure to pass the group join?', 'cn' => '确定通过加入班级？']
    ,'are_you_sure_to_reject_the_group_join' => ['en' => 'Are you sure to reject the group join?', 'cn' => '确定拒绝此班级加入？']
    ,'are_you_sure_to_rejudge_this_problem' => ['en' => 'Are you sure to rejudge this problem?', 'cn' => '你确定要重判此题目？']
    ,'author' => ['en' => 'Author', 'cn' => '作者']
    ,'available' => ['en' => 'Available', 'cn' => '可用']
    ,'home' => ['en' => 'Home', 'cn' => '主页']
    ,'back_to_home' => ['en' => 'Go Home', 'cn' => '返回主页']
    ,'can_not_be_null' => ['en' => 'can not be empty', 'cn' => '不可为空']
    ,'cancel' => ['en' => 'Cancel', 'cn' => '取消']
    ,'change_password' => ['en' => 'Change Password', 'cn' => '修改密码']
    ,'class' => ['en' => 'Class', 'cn' => '班级']
    ,'clone' => ['en' => 'Clone', 'cn' => '复制']
    ,'code_length' => ['en' => 'Code Length', 'cn' => '代码长度']
    ,'content' => ['en' => 'Content', 'cn' => '内容']
    ,'contest' => ['en' => 'Contest', 'cn' => '比赛']
    ,'contest_code_ended' => ['en' => 'Ended', 'cn' => '已结束']
    ,'contest_code_pending' => ['en' => 'Pending', 'cn' => '未开始']
    ,'contest_code_running' => ['en' => 'Running', 'cn' => '进行中']
    ,'contest_has_started' => ['en' => 'The contest has started.', 'cn' => '比赛已经开始']
    ,'contest_id' => ['en' => 'Contest ID', 'cn' => '比赛编号']
    ,'contest_not_exists' => ['en' => 'Contest Not Exists', 'cn' => '比赛不存在']
    ,'contest_password' => ['en' => 'Contest Password', 'cn' => '比赛密码']
    ,'current_time' => ['en' => 'Current Time', 'cn' => '当前时间']
    ,'delete' => ['en' => 'Delete', 'cn' => '删除']
    ,'description' => ['en' => 'Description', 'cn' => '描述']
    ,'day' => ['en' => 'Day', 'cn' => '天']
    ,'disable' => ['en' => 'Disable', 'cn' => '禁用']
    ,'disabled' => ['en' => 'Disabled', 'cn' => '不可用']
    ,'download' => ['en' => 'Download', 'cn' => '下载']
    ,'do_not_have_privilege' => ['en' => 'Do NOT have privilege', 'cn' => '没有访问权限']
    ,'edit' => ['en' => 'Edit', 'cn' => '编辑']
    ,'email' => ['en' => 'Email', 'cn' => 'Email']
    ,'enable' => ['en' => 'Enable', 'cn' => '启用']
    ,'enabled' => ['en' => 'Enabled', 'cn' => '可用']
    ,'end_time' => ['en' => 'End Time', 'cn' => '结束时间']
    ,'enter' => ['en' => 'Enter', 'cn' => '进入']
    ,'exe_time' => ['en' => 'Exe. Time', 'cn' => '运行时间']
    ,'file_name' => ['en' => 'File Name', 'cn' => '文件名']
    ,'file_size' => ['en' => 'File Size', 'cn' => '文件大小']
    ,'goto_login' => ['en' => 'Go to login', 'cn' => '前往登录']
    ,'goto_manage_problem_data' => ['en' => 'Go to manage the problem.', 'cn' => '前往管理问题数据']
    ,'goto_register' => ['en' => 'Go to register', 'cn' => '前往注册']
    ,'go_to_edit_problem' => ['en' => 'Go to edit the problem.', 'cn' => '前往编辑问题']
    ,'go_to_problem_preview' => ['en' => 'Go to view the problem.', 'cn' => '前往查看问题']
    ,'group' => ['en' => 'Group', 'cn' => '班级']
    ,'group_join_not_exists' => ['en' => 'Group join not exists', 'cn' => '班级加入记录不存在']
    ,'group_list' => ['en' => 'Group List', 'cn' => '班级列表']
    ,'group_notification_not_exists' => ['en' => 'Group notification not exists.', 'cn' => '班级公告不存在。']
    ,'group_not_exists' => ['en' => 'Group not exists', 'cn' => '班级不存在']
    ,'hint' => ['en' => 'Hint', 'cn' => '提示']
    ,'homework' => ['en' => 'Homework', 'cn' => '作业']
    ,'homework_list' => ['en' => 'Homework List', 'cn' => '作业列表']
    ,'input' => ['en' => 'Input', 'cn' => '输入']
    ,'join' => ['en' => 'Join', 'cn' => '加入']
    ,'justoj' => ['en' => 'JustOJ', 'cn' => '江西理工大学编程俱乐部']
    ,'keyword' => ['en' => 'Keyword', 'cn' => '关键字']
    ,'keywords' => ['en' => 'Keywords', 'cn' => '关键字']
    ,'language' => ['en' => 'Language', 'cn' => '语言']
    ,'login' => ['en' => 'Login', 'cn' => '登录']
    ,'login_success' => ['en' => 'Login Successfully', 'cn' => '登录成功']
    ,'logout' => ['en' => 'Logout', 'cn' => '注销']
    ,'mark' => ['en' => 'Mark', 'cn' => '成绩']
    ,'members' => ['en' => 'Members', 'cn' => '成员']
    ,'memory' => ['en' => 'Memory', 'cn' => '内存']
    ,'memory_limit' => ['en' => 'Memory Limit', 'cn' => '内存限制']
    ,'mygroup' => ['en' => 'My Group', 'cn' => '我的班级']
    ,'my_creation' => ['en' => 'My Creation', 'cn' => '我创建的']
    ,'my_join' => ['en' => 'My Join', 'cn' => '我加入的']
    ,'my_status' => ['en' => 'My Status', 'cn' => '我的状态']
    ,'name' => ['en' => 'Name', 'cn' => '名称']
    ,'news_list' => ['en' => 'News List', 'cn' => '新闻列表']
    ,'need_enroll' => ['en' => 'Need Enroll', 'cn' => '需要注册']
    ,'nickname' => ['en' => 'Nickname', 'cn' => '昵称']
    ,'fullname' => ['en' => 'Fullname', 'cn' => '姓名']
    ,'notifications' => ['en' => 'Notifications', 'cn' => '公告']
    ,'not_login' => ['en' => 'You are not login', 'cn' => '尚未登录']
    ,'no_such_problem' => ['en' => 'No such problem.', 'cn' => '问题不存在。']
    ,'operation' => ['en' => 'Operation', 'cn' => '操作']
    ,'output' => ['en' => 'Output', 'cn' => '输出']
    ,'paste_code' => ['en' => 'Paste', 'cn' => '贴代码']
    ,'pass' => ['en' => 'Pass', 'cn' => '通过']
    ,'password' => ['en' => 'Password', 'cn' => '密码']
    ,'password_again' => ['en' => 'Password Again', 'cn' => '重复密码']
    ,'password_and_password_again_must_be_same' => ['en' => 'Password and password again must be same.', 'cn' => '密码与确认密码必须相同。']
    ,'password_cant_be_empty' => ['en' => 'Password can not be empty.', 'cn' => '密码不可为空。']
    ,'password_has_been_changed' => ['en' => 'Password has been changed.', 'cn' => '密码已经修改.']
    ,'penalty' => ['en' => 'Penalty', 'cn' => '罚时']
    ,'personal_information' => ['en' => 'Personal Information', 'cn' => '个人信息']
    ,'phone' => ['en' => 'Phone', 'cn' => '电话']
    ,'please_input_memory_limit' => ['en' => 'Please Input Memory Limit', 'cn' => '请输入内存限制']
    ,'please_input_password' => ['en' => 'Please input password', 'cn' => '请输入密码']
    ,'please_input_password_again' => ['en' => 'Please input password again', 'cn' => '请输入重复密码']
    ,'please_input_source' => ['en' => 'Please Input Source', 'cn' => '请输入来源']
    ,'please_input_time_limit' => ['en' => 'Please Input Time Limit', 'cn' => '请输入时间限制']
    ,'please_input_title' => ['en' => 'Please Input Title', 'cn' => '请输入标题']
    ,'please_input_username' => ['en' => 'Please Input Username', 'cn' => '请输入用户名']
    ,'please_input_keyword_for_searching_username_or_nickname' => ['en' => 'Please input keyword for searching username or nickname', 'cn' => '请输入查找用户名或昵称的关键字']
    ,'preview_problems' => ['en' => 'Preview Problems', 'cn' => '预览问题']
    ,'privilege' => ['en' => 'Privilege', 'cn' => '权限']
    ,'privilege_code_private' => ['en' => 'Private', 'cn' => '私有']
    ,'privilege_code_public' => ['en' => 'Public', 'cn' => '公开']
    ,'problem' => ['en' => 'Problem', 'cn' => '问题']
    ,'problem_description' => ['en' => 'Problem Description', 'cn' => '题目描述']
    ,'problem_has_been_saved' => ['en' => 'Problem has been saved.', 'cn' => '问题已保存。']
    ,'problem_id' => ['en' => 'ProblemID', 'cn' => '问题编号']
    ,'problem_list' => ['en' => 'Problem List', 'cn' => '问题列表']
    ,'problem_not_exists' => ['en' => 'Problem not exists.', 'cn' => '问题不存在。']
    ,'rank' => ['en' => 'Rank', 'cn' => '排名']
    ,'rate' => ['en' => 'Rate', 'cn' => '比率']
    ,'register' => ['en' => 'Register', 'cn' => '注册']
    ,'reject' => ['en' => 'Reject', 'cn' => '拒绝']
    ,'rejected' => ['en' => 'Rejected', 'cn' => '已拒绝']
    ,'rejudge' => ['en' => 'Rejudge', 'cn' => '重判题目']
    ,'removed' => ['en' => 'Removed', 'cn' => '已移除']
    ,'reset' => ['en' => 'Reset', 'cn' => '重置']
    ,'result' => ['en' => 'Result', 'cn' => '结果']
    ,'result_code_ac' => ['en' => 'Accepted', 'cn' => '答案正确']
    ,'result_code_ce' => ['en' => 'Compile Error', 'cn' => '编译错误']
    ,'result_code_co' => ['en' => 'Compile OK', 'cn' => '编译通过']
    ,'result_code_compiling' => ['en' => 'Compiling', 'cn' => '正在编译']
    ,'result_code_mle' => ['en' => 'Memory Limit Exceed', 'cn' => '内存超限']
    ,'result_code_ole' => ['en' => 'Output Limit Exceed', 'cn' => '输出超限']
    ,'result_code_pe' => ['en' => 'Presentation Error', 'cn' => '格式错误']
    ,'result_code_pending' => ['en' => 'Pending', 'cn' => '等待判题']
    ,'result_code_re' => ['en' => 'Runtime Error', 'cn' => '运行错误']
    ,'result_code_rejuding' => ['en' => 'Rejudging', 'cn' => '等待重判']
    ,'result_code_running' => ['en' => 'Running', 'cn' => '正在运行']
    ,'result_code_so' => ['en' => 'Submit OK', 'cn' => '提交成功']
    ,'result_code_tle' => ['en' => 'Time Limit Exceed', 'cn' => '时间超限']
    ,'result_code_tr' => ['en' => 'Test RUN', 'cn' => '测试运行']
    ,'result_code_wa' => ['en' => 'Wrong Answer', 'cn' => '答案错误']
    ,'root' => ['en' => 'Root', 'cn' => '超级管理员']
    ,'root_tools' => ['en' => 'Root Tools', 'cn' => '超管工具']
    ,'run_id' => ['en' => 'RunID', 'cn' => '运行编号']
    ,'sample_input' => ['en' => 'Sample Input', 'cn' => '样例输入']
    ,'sample_output' => ['en' => 'Sample Output', 'cn' => '样例输出']
    ,'save' => ['en' => 'Save', 'cn' => '保存']
    ,'school' => ['en' => 'School', 'cn' => '学校']
    ,'search' => ['en' => 'Search', 'cn' => '搜索']
    ,'set_announcement' => ['en' => 'Set Announcement', 'cn' => '设置公告']
    ,'solution_not_exists' => ['en' => 'Solution Not Exists', 'cn' => '提交记录不存在']
    ,'source' => ['en' => 'Source', 'cn' => '来源']
    ,'source_code' => ['en' => 'Source Code', 'cn' => '源代码']
    ,'start_countdown' => ['en' => 'Start Countdown', 'cn' => '倒计时']
    ,'start_time' => ['en' => 'Start Time', 'cn' => '开始时间']
    ,'statistics' => ['en' => 'Statistics', 'cn' => '统计']
    ,'status' => ['en' => 'Status', 'cn' => '状态']
    ,'submit' => ['en' => 'Submit', 'cn' => '提交']
    ,'submit_code' => ['en' => 'Submit Code', 'cn' => '提交代码']
    ,'submit_time' => ['en' => 'Submit Time', 'cn' => '提交时间']
    ,'tasks' => ['en' => 'Tasks', 'cn' => '作业']
    ,'teacher' => ['en' => 'Teacher', 'cn' => '老师']
    ,'test_data' => ['en' => 'Test Data', 'cn' => '测试数据']
    ,'time_limit' => ['en' => 'Time Limit', 'cn' => '时间限制']
    ,'title' => ['en' => 'Title', 'cn' => '标题']
    ,'type' => ['en' => 'Type', 'cn' => '类型']
    ,'upload' => ['en' => 'Upload', 'cn' => '上传']
    ,'upload_file' => ['en' => 'Upload File', 'cn' => '上传文件']
    ,'user_login' => ['en' => 'User Login', 'cn' => '用户登录']
    ,'user_register' => ['en' => 'User Register', 'cn' => '用户注册']
    ,'username' => ['en' => 'Username', 'cn' => '用户名']
    ,'user_not_exists' => ['en' => 'User not exists', 'cn' => '用户不存在']
    ,'waiting_for_verify' => ['en' => 'Waiting for verify', 'cn' => '等待审核']
    ,'welcome_to_justoj' => ['en' => 'Welcome to JustOJ', 'cn' => '江西理工大学编程俱乐部']
    ,'wrong_password' => ['en' => 'Wrong Password', 'cn' => '密码错误']
    ,'forgot_password' => ['en' => 'Forgot Password', 'cn' => '忘记密码']
    ,'you_are_the_manager_of_this_group' => ['en' => 'Your are the manager of this group', 'cn' => '你是此班级的管理员']
    ,'you_have_request_join_the_group_already' => ['en' => 'You have request join the group already', 'cn' => '你已申请过加入此班级']
    ,'will_only_show_in_contest' => ['en' => 'Attention: This will only show in contest rank list.', 'cn' => '注：只会出现在比赛列表中']
];