version: '3'

services:
  db:
    image: mysql:8.0-oracle
    environment:
      MYSQL_ROOT_PASSWORD: justoj123456
      MYSQL_DATABASE: justoj
    ports:
      - '3306:3306'
    restart: always
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/justoj'
      - './.data/nginx-config:/etc/nginx/conf.d/default.conf:ro'
    restart: always
  php:
    image: ubuntu:20.04
    command: ['bash', '/start.bash']
    environment:
      DEBIAN_FRONTEND: noninteractive
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/justoj'
      - './.data/php-fpm-start.bash:/start.bash:ro'
      - './.data/.justoj-env:/var/www/justoj/.env'

